### ISSUE TITLE
Avoidable race condition for kolibri service

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri-server#23] opened 2019-08-07 21:10 UTC
**Identified problem :**
Upon installation of ```kolibri-server```, the ```kolibri``` package is installed and the ```kolibri.service``` is ```enabled```. This results in multiple simultaneous or successive attempts to start kolibri -

1. via the enabled ```kolibri.service```
2. via ```/etc/init.d/kolibri-server``` executed by ```kolibri-server.service```

Inside ```/etc/init.d/kolibri-server``` itself there are multiple calls to start kolibri [prior to starting nginx](https://github.com/learningequality/kolibri-server/blob/master/debian/kolibri-server.init#L57) and then in quick succession [during checking of nginx status](https://github.com/learningequality/kolibri-server/blob/master/debian/kolibri-server.init#L94), which too result in race conditions with large databases.
 
This in turn results in database locking errors visible in ```daemon.txt```. This is particularly experienced with reasonably sized databases wherein the time consuming vacuuming process is underway while a subsequent attempt is made to start Kolibri. With smaller databases, this logical oversight goes unnoticed.

**Proposed solution :**
Hence in the post-inst for kolibri-server, executing ```systemctl disable kolibri``` shall help avoid at least one possible cause of race scenario and refactoring of  ```/etc/init.d/kolibri-server``` may also help as there is no need to restart kolibri prior to nginx reload.

**Related:**
This is related to #19 since the 2nd vacuuming after a systemd call is completed conflicts with the subsequent systemd call due to db locking.

**Comment by jredrejo** [comment] 2019-08-21 15:13
@intelliant01 I don't like the idea of disabling a daemon in another's package postinst.
The changed done in https://github.com/learningequality/kolibri-server/commit/90d69f15f3cb8780c2b72c24fd0fc18c0ced5dc8 avoiding starting kolibri from systemd should be enough to solve all these problems. I have not been able to replicate them after it.

Feel free to reopen this issue if you still face the problem (minding the second point of https://github.com/learningequality/kolibri-server/issues/20#issuecomment-523139707 as well, that's a kind of duplicate of this issue)

**Closed as completed by jredrejo** 2019-08-21 15:13 UTC
