### ISSUE TITLE
Install and test report on Debian 9

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri-server#8] opened 2019-01-20 23:46 UTC
# Installation report on Debian 9

Summary:

  - I installed preview package `kolibri-network-layer_0.1-1_all.deb` on Debian
    with difficulties (instructions in kolibri docs seem to assume Ubuntu, not Debian).

  - After getting it to work the uWSGI workers kept dying for no apparent reason
    and were not being respawned

## Context

Debian VM on a Mac host:

    root@debian9vm:~# uname -a
    Linux debian9vm 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

    root@debian9vm:~# cat /etc/debian_version
    9.6

## Prerequisites Steps

I followed the [section on Debian/Kolibri in the docs](https://kolibri.readthedocs.io/en/latest/install.html#debian-ubuntu), but also taking parts of commands from the Raspberry PI instructions.

Here are the Debian-specific instructions:

```
sudo apt-get install software-properties-common dirmngr
sudo su -c 'echo "deb http://ppa.launchpad.net/learningequality/kolibri/ubuntu cosmic main" > /etc/apt/sources.list.d/learningequality-ubuntu-kolibri-cosmic.list'
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys DC5BAA93F9E4AE4F0411F97C74F88ADB3194DD81
sudo apt-get update
sudo apt-get install kolibri
```

Overall, given the four different workarounds needed for Debian to use the `.deb` from the PPA repo, we should consider giving special instructions for Debian users and Ubuntu users.
I've opened an issue on kolibri-docs for this: https://github.com/learningequality/kolibri-docs/issues/60

## Install Kolibri
 
    root@debian9vm:~# apt-get install kolibri
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    The following additional packages will be installed:
      python3-cffi-backend python3-cryptography python3-idna python3-pyasn1 python3-setuptools
    Suggested packages:
      python-cryptography-doc python3-cryptography-vectors doc-base python-setuptools-doc
    The following NEW packages will be installed:
      kolibri python3-cffi-backend python3-cryptography python3-idna python3-pyasn1 python3-setuptools
    0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
    Need to get 42.4 MB of archives.
    After this operation, 227 MB of additional disk space will be used.
    Do you want to continue? [Y/n]
    ...
    ... [ kolibri ../41.8 MB]

I checked and it was running, completed the setup wizard.

## Install kolibri-network-layer

I first copied the .deb that José sent me by email to the VM, then ran:

    root@debian9vm:~# dpkg -i kolibri-network-layer_0.1-1_all.deb
    Selecting previously unselected package kolibri-network-layer.
    (Reading database ... 62308 files and directories currently installed.)
    Preparing to unpack kolibri-network-layer_0.1-1_all.deb ...
    Unpacking kolibri-network-layer (0.1-1) ...
    dpkg: dependency problems prevent configuration of kolibri-network-layer:
     kolibri-network-layer depends on nginx-light | nginx; however:
      Package nginx-light is not installed.
      Package nginx is not installed.
     kolibri-network-layer depends on uwsgi; however:
      Package uwsgi is not installed.
     kolibri-network-layer depends on uwsgi-plugin-python3; however:
      Package uwsgi-plugin-python3 is not installed.
    dpkg: error processing package kolibri-network-layer (--install):
     dependency problems - leaving unconfigured
    Processing triggers for systemd (232-25+deb9u8) ...
    Errors were encountered while processing:
     kolibri-network-layer

and after 

    root@debian9vm:~# apt-get -f install
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    Correcting dependencies... Done
    The following additional packages will be installed:
      libjansson4 libmatheval1 libnginx-mod-http-echo libpgm-5.2-0 libpython3.5 libsodium18 libyaml-0-2 libzmq5 nginx-common nginx-light uwsgi
      uwsgi-core uwsgi-plugin-python3
    Suggested packages:
      fcgiwrap nginx-doc ssl-cert nginx-full | cherokee | libapache2-mod-proxy-uwsgi | libapache2-mod-uwsgi | libapache2-mod-ruwsgi uwsgi-plugins-all
      uwsgi-extra python3-uwsgidecorators
    The following NEW packages will be installed:
      libjansson4 libmatheval1 libnginx-mod-http-echo libpgm-5.2-0 libpython3.5 libsodium18 libyaml-0-2 libzmq5 nginx-common nginx-light uwsgi
      uwsgi-core uwsgi-plugin-python3
    0 upgraded, 13 newly installed, 0 to remove and 0 not upgraded.
    1 not fully installed or removed.
    Need to get 3,339 kB of archives.
    After this operation, 10.3 MB of additional disk space will be used.
    Do you want to continue? [Y/n]

Versions installed:
```
Get:1 http://debian.mirror.rafal.ca/debian stretch/main amd64 libjansson4 amd64 2.9-1 [28.1 kB]
Get:2 http://debian.mirror.rafal.ca/debian stretch/main amd64 libmatheval1 amd64 1.1.11+dfsg-3 [22.8 kB]
Get:3 http://debian.mirror.rafal.ca/debian stretch/main amd64 libyaml-0-2 amd64 0.1.7-2 [47.6 kB]
Get:4 http://debian.mirror.rafal.ca/debian stretch/main amd64 libpgm-5.2-0 amd64 5.2.122~dfsg-2 [157 kB]
Get:6 http://debian.mirror.rafal.ca/debian stretch/main amd64 libsodium18 amd64 1.0.11-2 [161 kB]
Get:10 http://debian.mirror.rafal.ca/debian stretch/main amd64 uwsgi-core amd64 2.0.14+20161117-3+deb9u2 [558 kB]
Get:11 http://debian.mirror.rafal.ca/debian stretch/main amd64 uwsgi amd64 2.0.14+20161117-3+deb9u2 [47.3 kB]
Get:12 http://debian.mirror.rafal.ca/debian stretch/main amd64 libpython3.5 amd64 3.5.3-1+deb9u1 [1,372 kB]
Get:13 http://debian.mirror.rafal.ca/debian stretch/main amd64 uwsgi-plugin-python3 amd64 2.0.14+20161117-3+deb9u2 [106 kB]
Get:5 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 nginx-common all 1.10.3-1+deb9u2 [105 kB]
Get:7 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 libnginx-mod-http-echo amd64 1.10.3-1+deb9u2 [97.1 kB]
Get:8 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 nginx-light amd64 1.10.3-1+deb9u2 [436 kB]
Get:9 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 libzmq5 amd64 4.2.1-4+deb9u1 [201 kB]
```

After this install step cherrypy was still on port `8080`, but nothing was running on `8888`.

After running `service nginx reload`, nginx + uWSGI appeared on port `8888`.

TODO: need to run `service nginx reload` as part of post install script.

## Service status weirdness

One weird thing is that the `kolibri-network-layer` service is reported as not 
running `[-]` even though it's working fine:

    root@debian9vm:~# service --status-all
     [ - ]  anacron
     [ - ]  bluetooth
     [ - ]  console-setup.sh
     [ + ]  cron
     [ + ]  dbus
     [ - ]  hwclock.sh
     [ - ]  keyboard-setup.sh
     [ + ]  kmod
     [ + ]  kolibri
     [ - ]  kolibri-network-layer
     [ + ]  networking
     [ + ]  nginx
     [ + ]  procps
     [ + ]  rsyslog
     [ + ]  ssh
     [ + ]  udev
     [ + ]  unattended-upgrades
     [ + ]  uwsgi

checkin status says:

    root@debian9vm:~# service kolibri-network-layer status
     ● kolibri-network-layer.service - A high performance web server setup for Kolibri
        Loaded: loaded (/lib/systemd/system/kolibri-network-layer.service; enabled; vendor preset: enabled)
        Active: inactive (dead) since Sun 2019-01-20 16:57:28 EST; 36s ago
       Process: 4644 ExecStop=/etc/init.d/kolibri-network-layer stop (code=exited, status=0/SUCCESS)
       Process: 4626 ExecStart=/etc/init.d/kolibri-network-layer start (code=exited, status=0/SUCCESS)
      Main PID: 4626 (code=exited, status=0/SUCCESS)

     Jan 20 16:56:58 debian9vm systemd[1]: Started A high performance web server setup for Kolibri.
     Jan 20 16:56:58 debian9vm kolibri-network-layer[4626]: [uWSGI] getting INI configuration from /etc/kolibri/kolibri.ini
     Jan 20 16:56:58 debian9vm kolibri-network-layer[4626]: reload: unrecognized service

The process tree looks like this:

    root@debian9vm:~# pstree -ap
    systemd,1
      .
      ├─kolibri,3781 /usr/bin/kolibri start
      │   ├─{kolibri},3782
      │   ├─{kolibri},3783
            ...
      │   └─{kolibri},3807
      .
      ├─kolibri-network,4644 /etc/init.d/kolibri-network-layer stop
      │   └─start-stop-daem,4652 --stop --quiet --retry=TERM/30/KILL/5 --pidfile /var/run/kolibri-network-layer/uwsgi.pid --name uwsgi
      .
      ├─nginx,4245
      │   └─nginx,4246
      .
      └─uwsgi,4641 --ini /etc/kolibri/kolibri.ini --uid=kolibri --env=KOLIBRI_HOME=/var/kolibri/.kolibri ...
          ├─uwsgi,4658 --ini /etc/kolibri/kolibri.ini --uid=kolibri --env=KOLIBRI_HOME=/var/kolibri/.kolibri ...
          ├─uwsgi,4659 --ini /etc/kolibri/kolibri.ini --uid=kolibri --env=KOLIBRI_HOME=/var/kolibri/.kolibri ...
          ├─uwsgi,4660 --ini /etc/kolibri/kolibri.ini --uid=kolibri --env=KOLIBRI_HOME=/var/kolibri/.kolibri ...
          └─uwsgi,4661 --ini /etc/kolibri/kolibri.ini --uid=kolibri --env=KOLIBRI_HOME=/var/kolibri/.kolibri ...

## Crashes

Overall the current preview package did not work because uWSGI workers kept exiting.

### Crash one

After a few requests (to content from partial import of Blockly Games) the uWSGI
processes die, with the following useful info in the logs:

    root@debian9vm:~#  tail -f /var/kolibri/.kolibri/uwsgi.log
    INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
    WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55894a95b150 pid: 7531 (default app)
    *** uWSGI is running in multiple interpreter mode ***
    spawned uWSGI master process (pid: 7531)
    spawned uWSGI worker 1 (pid: 7547, cores: 1)
    spawned uWSGI worker 2 (pid: 7548, cores: 1)
    spawned uWSGI worker 3 (pid: 7549, cores: 1)
    spawned uWSGI worker 4 (pid: 7550, cores: 1)
    spawned uWSGI worker 5 (pid: 7551, cores: 1)
    mapping worker 1 to CPUs: 0
    mapping worker 2 to CPUs: 0
    mapping worker 3 to CPUs: 0
    mapping worker 4 to CPUs: 0
    mapping worker 5 to CPUs: 0
    unable to find requested cheaper algorithm, falling back to spare
    worker 1 killed successfully (pid: 7547)
    uWSGI worker 1 cheaped.

    [pid: 7551|app: 0|req: 1/1] 192.168.0.100 () {46 vars in 806 bytes} [Sun Jan 20 17:47:54 2019] GET /learn/ => generated 10565 bytes in 518 msecs (HTTP/1.1 200) 10 headers in 498 bytes (1 switches on core 0)
    [pid: 7550|app: 0|req: 1/2] 192.168.0.100 () {48 vars in 1010 bytes} [Sun Jan 20 17:47:55 2019] GET /api/auth/facility/?1548024475770=1548024475770 => generated 241 bytes in 164 msecs (HTTP/1.1 200) 9 headers in 302 bytes (2 switches on core 0)
    [pid: 7551|app: 0|req: 2/3] 192.168.0.100 () {48 vars in 994 bytes} [Sun Jan 20 17:47:56 2019] GET /api/auth/session/current/?active=false => generated 144 bytes in 6 msecs (HTTP/1.1 200) 9 headers in 336 bytes (1 switches on core 0)
    [pid: 7550|app: 0|req: 2/4] 192.168.0.100 () {50 vars in 1062 bytes} [Sun Jan 20 17:47:56 2019] POST /api/logger/contentsessionlog/?1548024476612=1548024476612 => generated 223 bytes in 30 msecs (HTTP/1.1 201) 7 headers in 241 bytes (1 switches on core 0)

    io.UnsupportedOperation: fileno
    io.UnsupportedOperation: fileno

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/handlers/wsgi.py", line 167, in __call__
      response = environ['wsgi.file_wrapper'](response.file_to_stream)
    SystemError: <built-in function uwsgi_sendfile> returned a result with an error set

    [pid: 7550|app: 0|req: 3/5] 192.168.0.100 () {42 vars in 984 bytes} [Sun Jan 20 17:47:58 2019] GET /zipcontent/0a688979cbf9508c53468632e9a60ef3.zip/third-party/blockly/media/disconnect.wav => generated 0 bytes in 52 msecs (HTTP/1.1 200) 10 headers in 415 bytes (0 switches on core 0)

    ...
    (several more like the above)
    ...

    Sun Jan 20 17:48:04 2019 - uWSGI worker 5 screams: UAAAAAAH my master disconnected: i will kill myself !!!
    Sun Jan 20 17:48:04 2019 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
    Sun Jan 20 17:48:04 2019 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
    Sun Jan 20 17:48:04 2019 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!

It seems the culprit is the https://github.com/unbit/uwsgi/issues/1126#issuecomment-166687767
see also https://uwsgi-docs.readthedocs.io/en/latest/Changelog-2.0.12.html#wsgi-disable-file-wrapper

Appending the following line to `/etc/kolibri/kolibri.ini` fixes this issue:

    [uwsgi]
    ...
    wsgi-disable-file-wrapper = true

### Crash two

After vising a few more pages another error brought down the uWSGI processes:

    OSError: write error
    [pid: 8335|app: 0|req: 2/6] 192.168.0.100 () {48 vars in 1112 bytes} [Sun Jan 20 18:13:58 2019] GET /api/content/contentnode/46af3fcdf8425a59be74c7285a1bb26d/next_content/?contentCacheKey=1548021628 => generated 0 bytes in 415 msecs (HTTP/1.1 200) 8 headers in 0 bytes (0 switches on core 0)
    Sun Jan 20 18:13:58 2019 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /api/content/contentnode_slim/46af3fcdf8425a59be74c7285a1bb26d/ancestors/?contentCacheKey=1548021628 (ip 192.168.0.100) !!!
    Sun Jan 20 18:13:58 2019 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 296] during GET /api/content/contentnode_slim/46af3fcdf8425a59be74c7285a1bb26d/ancestors/?contentCacheKey=1548021628 (192.168.0.100)

## Conclusion

Overall uWSGI processes seem to crash often with no apparent reason

I used

    service kolibri-network-layer restart

to restart the workers several times, but after a few requests it seems to crash.

Happy to test next version again.

**Comment by benjaoming** [comment] 2019-01-21 00:07
> add-apt-repository not installed

Your fix is literally in the docs :)

![image](https://user-images.githubusercontent.com/374612/51446892-4ecd2a80-1d18-11e9-9e9d-df96e12e783e.png)

> 2. Adding the Kolibri PPA sets the wrong distribution:

This is also well-known, but currently we only list the solution in the RPI docs.

![image](https://user-images.githubusercontent.com/374612/51446898-6dcbbc80-1d18-11e9-9e66-045bc5687451.png)

> 3. Missing dirmngr

This is also in the RPI docs.

> 4. Missing gpg key

Also in RPI docs

------------------

In order for this to be more actionable, I would suggest opening up an issue in kolibri-docs to have targeted Debian documentation. It can be made interchangeable with the RPI docs.

Everything else for `kolibri` should be in the `kolibri-installer-debian` repo.

The rest is for this package :)

**Comment by ivanistheone** [comment] 2019-01-21 00:17
Hi @benjaoming  oups --- I should read more ;)  3 out of the 4 install difficulties on Debian were indeed in the docs. All except for this one:

> Missing gpg key
> Also in RPI docs

The command in the docs for adding the key is:

    # apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DC5BAA93F9E4AE4F0411F97C74F88ADB3194DD81

On Debian it fails with rather uninformative

```
Executing: /tmp/apt-key-gpghome.IBlFaCMfTu/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys DC5BAA93F9E4AE4F0411F97C74F88ADB3194DD81
gpg: keyserver receive failed: Server indicated a failure
```

The following alternative protocol for the keyserver worked:

```
# apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys DC5BAA93F9E4AE4F0411F97C74F88ADB3194DD81

Executing: /tmp/apt-key-gpghome.jlUo7R5W1m/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys DC5BAA93F9E4AE4F0411F97C74F88ADB3194DD81
gpg: key 74F88ADB3194DD81: public key "Launchpad PPA for Foundation for Learning Equality" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

Note the `hkp://` protocol and explicit port `:80` for the `--keyserver` option.

**Comment by jredrejo** [comment] 2019-01-21 08:47
@ivanistheone  thanks very much for your tests.
I will concentrate only on kolibri-server comments by now because I prefer to concentrate on one thing at a time. 
Please, help me to clarify all what you found:
1. Installation steps worked fine , excepting `service nginx reload` is needed in the postinst script.
2. After installing the daemon did not start , after restarting it you saw it running, right?
3. `usgi-disable-file-wrapper = true`  fixed the problems you had due to an uwsgi bug
4. Later errors killed uwsgi (or only some of its processes? I am not sure if I understand it well)

I am not able to reproduce points 3 & 4. Could you add information about what channel/content where you reproducing when they happened.

**Comment by ivanistheone** [comment] 2019-01-21 14:05
Hi @jredrejo  Yes you're correct about 1/2/3/4. Sorry for the rambling bug report without specifics.
Here are some more comments:

> 1. Installation steps worked fine , excepting service nginx reload is needed in the postinst script.

Correct.

> 2. After installing the daemon did not start , after restarting it you saw it running, right?

Yes. As you can see in the `pstree` output, there was the `kolibri` processes, `kolibri-network`, `nginx`,  and several `uwsgi`.

The weird things worth reporting here is that systemd thinks the service `kolibri-network-layer` is not running even though the `kolibri-network` was running fine:
```
# service --status-all
...
 [ - ]  kolibri-network-layer
 [ + ]  uwsgi
```
but that's not a real problem, just a bit confusing.



> 3. usgi-disable-file-wrapper = true fixed the problems you had due to an uwsgi bug

Yeah when I added that option the send file `io.UnsupportedOperation: fileno` stopped.
Note these errors come up later when I tried to load content from a HTML5Zip
(From a partial import of the [Blockly Games](https://studio.learningequality.org/channels/e409b964366a59219c148f2aaa741f43/view/e409b96) channel) and independed of problem 4.


> 4. Later errors killed uwsgi (or only some of its processes? I am not sure if I understand it well)

All processes die, and when I check pstree there are no more uwsgi processes
I suspect the version in Debian, `uwsgi-core` and `uwsgi` are  2.0.14+20161117-3+deb9u2, are old...

I didn't find any useful info to report from the log but here it is anyway for reference:

```
*** Starting uWSGI 2.0.14-debian (64bit) on [Mon Jan 21 08:53:55 2019] ***
compiled with version: 6.3.0 20170516 on 17 March 2018 15:41:47
os: Linux-4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27)
nodename: debian9vm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /
writing pidfile to /var/run/kolibri-network-layer/uwsgi.pid
detected binary path: /usr/bin/uwsgi-core
setgid() to 33
setuid() to 108
chdir() to /usr/lib/python3/dist-packages/
your processes number limit is 23800
limiting address space of processes...
your process address space limit is 536870912 bytes (512 MB)
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers ***
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /tmp/kolibri_uwsgi.sock fd 3
Python version: 3.5.3 (default, Sep 27 2018, 17:25:39)  [GCC 6.3.0 20170516]
Python main interpreter initialized at 0x5581bb847150
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1237056 bytes (1208 KB) for 16 cores
*** Operational MODE: preforking ***
added /usr/lib/python3/dist-packages/kolibri/dist/ to pythonpath.
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x5581bb847150 pid: 794 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 794)
spawned uWSGI worker 1 (pid: 810, cores: 1)
spawned uWSGI worker 2 (pid: 811, cores: 1)
spawned uWSGI worker 3 (pid: 812, cores: 1)
spawned uWSGI worker 4 (pid: 813, cores: 1)
spawned uWSGI worker 5 (pid: 814, cores: 1)
unable to find requested cheaper algorithm, falling back to spare
mapping worker 3 to CPUs: 0
mapping worker 2 to CPUs: 0
mapping worker 4 to CPUs: 0
mapping worker 5 to CPUs: 0
mapping worker 1 to CPUs: 0
worker 1 killed successfully (pid: 810)
uWSGI worker 1 cheaped.

# ^ ^ ^ on startup

# then on first request  \/  \/  \/

[pid: 814|app: 0|req: 1/1] 192.168.0.100 () {44 vars in 841 bytes} [Mon Jan 21 08:54:12 2019] GET / => generated 0 bytes in 286 msecs (HTTP/1.1 302) 7 headers in 256 bytes (1 switches on core 0)
[pid: 813|app: 0|req: 1/2] 192.168.0.100 () {44 vars in 809 bytes} [Mon Jan 21 08:54:12 2019] GET /user/ => generated 9992 bytes in 614 msecs (HTTP/1.1 200) 10 headers in 497 bytes (1 switches on core 0)
[pid: 814|app: 0|req: 2/3] 192.168.0.100 () {46 vars in 1018 bytes} [Mon Jan 21 08:54:13 2019] GET /api/auth/session/current/?active=false => generated 144 bytes in 12 msecs (HTTP/1.1 200) 9 headers in 336 bytes (2 switches on core 0)
[pid: 814|app: 0|req: 3/4] 192.168.0.100 () {44 vars in 881 bytes} [Mon Jan 21 08:54:21 2019] GET /guestaccess/ => generated 0 bytes in 11 msecs (HTTP/1.1 302) 6 headers in 182 bytes (1 switches on core 0)
[pid: 813|app: 0|req: 2/5] 192.168.0.100 () {44 vars in 869 bytes} [Mon Jan 21 08:54:21 2019] GET /learn/ => generated 10531 bytes in 23 msecs (HTTP/1.1 200) 10 headers in 498 bytes (1 switches on core 0)
[pid: 814|app: 0|req: 4/6] 192.168.0.100 () {46 vars in 1035 bytes} [Mon Jan 21 08:54:21 2019] GET /api/auth/facility/?1548078863997=1548078863997 => generated 231 bytes in 18 msecs (HTTP/1.1 200) 9 headers in 302 bytes (1 switches on core 0)
[pid: 813|app: 0|req: 3/7] 192.168.0.100 () {46 vars in 1019 bytes} [Mon Jan 21 08:54:22 2019] GET /api/auth/session/current/?active=false => generated 144 bytes in 6 msecs (HTTP/1.1 200) 9 headers in 336 bytes (1 switches on core 0)
[pid: 814|app: 0|req: 5/8] 192.168.0.100 () {46 vars in 1067 bytes} [Mon Jan 21 08:54:22 2019] GET /api/content/channel/?available=true&contentCacheKey=1548031254 => generated 2 bytes in 19 msecs (HTTP/1.1 200) 8 headers in 260 bytes (1 switches on core 0)
Mon Jan 21 08:54:25 2019 - uWSGI worker 5 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Mon Jan 21 08:54:25 2019 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Mon Jan 21 08:54:25 2019 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Mon Jan 21 08:54:25 2019 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
```

This is on a VirtualBox VM, on mac host.

**Comment by benjaoming** [comment] 2019-01-21 14:31
Thanks @ivanistheone - I was making an assumption about the GPG issue. Have fixed it here:

https://github.com/learningequality/kolibri-docs/pull/61

**Comment by indirectlylit** [comment] 2019-03-25 20:58
can we break this issue apart into any outstanding individual issues? For any that are critical to our initial release, let's tag them with milestone [v0.1.0](https://github.com/learningequality/kolibri-server/milestone/1)

**Comment by jredrejo** [comment] 2019-04-04 07:58
@ivanistheone all these issues have been fixed. Could you do another test to confirm it?

**Comment by benjaoming** [comment] 2020-04-15 14:41
Just re-read this, I believe it is fixed now. We are supporting all flavors of Raspbian, so imagining that it's going quite okay now.

Cheers all :tada:

**Closed as completed by benjaoming** 2020-04-15 14:41 UTC
